/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cppfaultDetect_cppfaultDetect */

#ifndef _Included_cppfaultDetect_cppfaultDetect
#define _Included_cppfaultDetect_cppfaultDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cppfaultDetect_cppfaultDetect
 * Method:    fault_detect
 * Signature: ([C[[DI)I
 */
JNIEXPORT jint JNICALL Java_cppfaultDetect_cppfaultDetect_fault_1detect
  (JNIEnv *, jclass, jcharArray, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
